[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://campus-tudor-vladimirescu-2022.herokuapp.com/api/v1/"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://campus-tudor-vladimirescu-2022.herokuapp.com/api/v1/"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://campus-tudor-vladimirescu-2022.herokuapp.com/api/v1/"